imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        path: "%kernel.var_dir%/test_data.sqlite"

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    providers:
        fake:
            id: tests.fake_user_provider

    firewalls:
        secure:
            provider: fake
            http_basic: ~

        admin_secure:
            provider: fake
            http_basic: ~

services:
    tests.fake_user_provider:
        class: tests\Security\FakeUserProvider



